swami/libinstpatch

libinstpatch/CMakeLists.txt, libinstpatch/IpatchDLS2.c, libinstpatch/IpatchDLSReader.c, libinstpatch/IpatchFile.c, libinstpatch/IpatchFileBuf.c, libinstpatch/IpatchGigRegion.c, libinstpatch/IpatchItem.c, libinstpatch/IpatchIter.c, libinstpatch/IpatchRiff.c, libinstpatch/IpatchSF2.c, libinstpatch/IpatchSF2Reader.c, libinstpatch/IpatchSF2VoiceCache.c, libinstpatch/IpatchSF2VoiceCache_DLS.c, libinstpatch/IpatchSF2VoiceCache_Gig.c, libinstpatch/IpatchSF2VoiceCache_VBank.c, libinstpatch/IpatchSF2Writer.c, libinstpatch/IpatchSLIWriter.c, libinstpatch/IpatchSampleData.c, libinstpatch/IpatchSampleStoreSplit24.c, libinstpatch/IpatchSampleStoreSwap.c, libinstpatch/IpatchSampleStoreVirtual.c, libinstpatch/IpatchSampleTransform.c, libinstpatch/IpatchSndFile.c, libinstpatch/IpatchUnit_DLS.c, libinstpatch/IpatchUnit_SF2.c, libinstpatch/IpatchVBank.c, libinstpatch/IpatchVBankRegion.c, libinstpatch/IpatchXml.c, libinstpatch/sample.c, libinstpatch/util.c
1) adding a global definition for Windows to suppress deprecated functions warnings.
2)Cleanup a bunch of warning mainly by setting explicit casting:
- explicit cast on signed/unsigned.
- explicit cast when reducing format (i.e double to float).
3)removing return value on function defined `void function()`
4)renaming Windows i/o files functions.
=> Cleanup warnings

CMakeLists.txt, config.h.cmake, libinstpatch/IpatchFile.c, libinstpatch/IpatchSF2Reader.c, libinstpatch/IpatchSLIReader.c, libinstpatch/IpatchSample.c, libinstpatch/IpatchSampleStoreSwap.c, libinstpatch/ipatch_priv.h
1) Adding checking of Windows headers file `i.o.h` at CMake time.
2) Moving include of O.S headers files in `ipatch_priv.h`.
3)Adding macros for files i/o: `IPATCH_FD_READ(), IPATCH_FD_WRITE(), IPATCH_FD_LSEEK(),
IPATCH_FD_CLOSE()`.
=> Configure O.S includes files at Cmake time:

libinstpatch/CMakeLists.txt
This fix compilation errors when building libswami target.
=> Missing installed include file compat.h

libinstpatch/libinstpatch.def, utils/CMakeLists.txt, utils/riff_dump.c
This support adds arguments parsing useful for any console application example using libinstpatch library.
Actually riff_dump is one of these executable example that use getopt.
=> Add getopt support for Windows

utils/CMakeLists.txt, utils/riff_dump.c
This PR replace PR https://github.com/swami/libinstpatch/pull/23 which must be ignored.
Getopt support is removed from CMakeLists.txt. 
riff_dump command line executable makes use of Glib options parser instead of getopt.  
This fix #19.
=> GLib parser

libinstpatch/misc.c
This fix a side effect introduced by commit b45b2db for which Windows libinstpatch dll is linked with static version of runtime libraries (option Multithread (/MT)) instead of DLL multithread option (/MD).
In this case, even if the application call `setlocale()` function before calling any `ipatch_xml_xxxx_decode_xxxx_func()`, these decode functions will ignore the effect of `setlocale()` leading in float number not properly decoded.
This commit fix this issue by integrating call to `setlocale()` inside `ipatch_init()`.
=> Integrate setlocale() in libinstpatch dll:

libinstpatch/IpatchSF2Gen.h, libinstpatch/IpatchSF2IZone.c
This PR fixes issue https://github.com/swami/swami/issues/12
- IPATCH_SF2_GEN_SAMPLE_MODE_LOOP_RELEASE value that must be 3 (instead of 2).
- Also, enum IPATCH_SF2_GEN_SAMPLE_MODE_LOOP_RELEASE value must be added
(set to 2) because it should be interpreted as "loop none".
(sfspec24.pdf - p 36 - generator sampleModes (54)).
=>  Bug in IpatchSF2GenSampleModes enum.

libinstpatch/IpatchFile.h, libinstpatch/IpatchFileBuf.c
to fix an overflow in implicit constant conversion.
=> Changed argument in ipatch_file_buf_memset to uchar

libinstpatch/IpatchConverter.c
by passing an empty va_list, rather than NULL
=> Fix build on ARM and PPC

libinstpatch/IpatchState.c, libinstpatch/IpatchState.h, libinstpatch/IpatchStateGroup.c, libinstpatch/IpatchStateGroup.h, libinstpatch/IpatchStateItem.c, libinstpatch/IpatchStateItem.h, libinstpatch/IpatchState_types.c, libinstpatch/IpatchState_types.h, libinstpatch/libinstpatch.h.in, libinstpatch/version.h.in, tests/sample_list_test.c, tests/sample_test.c
Some of the file headers incorrectly state a GPL license. From my understanding, all source code under `libinstpatch/` should be LGPL licensed. This PR consistently changes to license to LGPL.
@Element-Green @elementgreen Acknowledge please.
=> Inconsistent licensing in file headers

libinstpatch/IpatchConverter.c
The variable `empty `being a function parameter, this PR fix a potential violation access.
Note: this was discovered by a compiler warning.
=> Fix variable used but not initialized.

libinstpatch/IpatchContainer.c, libinstpatch/IpatchContainer_notify.c, libinstpatch/IpatchConverter.c, libinstpatch/IpatchDLS2Info.c, libinstpatch/IpatchDLS2Sample.c, libinstpatch/IpatchFile.c, libinstpatch/IpatchItem.c, libinstpatch/IpatchItemProp.c, libinstpatch/IpatchParamProp.c, libinstpatch/IpatchSF2Gen.c, libinstpatch/IpatchSampleData.c, libinstpatch/IpatchSampleStoreSwap.c, libinstpatch/IpatchTypeProp.c, libinstpatch/IpatchUnit.c, libinstpatch/IpatchXmlObject.c, libinstpatch/libinstpatch.def, libinstpatch/misc.c, libinstpatch/util.c
The new function `ipatch_deinit() `is incorporated in `ipatch_close()` function API.
- Typically the application should call `ipatch_init() `before using any other functions.
- Then the application should call `ipatch_close() `when finished. This ensures freeing the memory allocated during ipatch_init().
Note: `ipatch_deinit()` has been incorporated in` ipatch_close() `because ipatch_close() is already a function API. This avoid changing actual version number.
=> Add deinitialization function ipatch_deinit()

libinstpatch/IpatchSF2VoiceCache.c
This PR fixes 3 issues
fix 1:  issue that occurs when a `IpatchSF2VoiceCache` object is freed.
For example using swami:
After loading a soundfont , playing some notes on one instrument zone than playing notes on another instrument zone,... such a `IpatchSF2VoiceCache` is used by the `fluidsynth plugin`. Then when the application exits this `IpatchSF2VoiceCache` is freed when `voice_cache_hash` is freed. This produces most critical messages:
`** (swami1.exe:7248): CRITICAL **: file ..IpatchSampleStoreCache.c: line 306: assertion IPATCH_IS_SAMPLE_STORE_CACHE (store) failed`
This is because when`IpatchSF2VoiceCache` is freed, `ipatch_sample_store_cache_close(store) `is called (via `cache->voice_user_data_destroy()`) and `store`parameter is no more valid because it is already freed before …
=> fix finalize operation in ipatch_sf2_voice_cache_finalize()

libinstpatch/IpatchItem.c
During a **copy/paste** of `instrument zones` in an `Instrument` (or **copy/paste** of `preset zones` in a `Preset`), paste operation fails. For example in **swami**  following critical messages occur.
- ** (swami1.exe:6236): CRITICAL **: file ..\..\..\libinstpatch-1.0.0\libinstpatch\IpatchItem.c: line 1166: assertion `link_func != NULL' failed
- ** (swami1.exe:6236): CRITICAL **: file ..\..\..\swami-2.0.0\src\swamigui\SwamiguiTreeStorePatch.c: line 367: assertion `title != NULL' failed.
The bug is in` ipatch_item_copy_link_func()`. This function is called by `ipatch_item_duplicate()` or `ipatch_item_duplicate_link_func()`. In the case of `ipatch_item_duplicate()`, the function is called by `ipatch_item_copy()` using the class method `klass->copy(dest, src, NULL, NULL)`.
As the method …
=> Fix a bug in paste operations.

libinstpatch/misc.c
This counter is necessary, when the application makes use of `multiples libraries` each dependent of `libinstpatch`. Examples: 
- `Swami `is dependent of `libinstpatch `and `fluidsynth`. `fluidsynth `could be optionally dependent of `libinstpatch`. In this case `libinstpatch `is owned twice (by `swami `and by `fluidsynth`).
- For an application only dependent of `fluidsynth`, `libinstpatch `is only owned by `fluidsynth`.
- For an application only dependent of `libinstpatch`, `libinstpatch `is only owned by this application.
This counter ensures that internal `initialization `(or `deinitialization`) is done only one time.
This is required because `libinstpatch `is dependent of `GObject` which doesn't accept that the same `Gtype` be registered multiple times.
=> Adding a safe reference counter for initialization/deinitialization

libinstpatch/IpatchSampleStoreSwap.c
This is the same as https://github.com/swami/libinstpatch/pull/51/ without commit ccf5dd8
=> fix memory violation access on swap file for Windows

azure-pipelines.yml, libinstpatch/CMakeLists.txt
Make sure the CI build produces PDBs on Windows and install them if existing.
=> CI Debug Windows build

libinstpatch/IpatchSLIInst.h, libinstpatch/IpatchSLIInst_CatMaps.c, libinstpatch/libinstpatch.def
-ipatch_sli_inst_get_cat_map().
-ipatch_sli_inst_get_cat_strings().
This functions allow libinstpatch to be called as a shared library.
This allows swami to access table in libinstpatch without violation access (PR https://github.com/swami/swami/pull/56 ).
=> Add getter functions for SLI soundfont

libinstpatch/IpatchDLS2Info.c
This PR fixes issue https://github.com/swami/swami/issues/55 point 2.3.
-  Because **bag** data belongs to original `IpatchDLS2 object`, when **newinfo** will be freed this will corrupt original IpatchDLS2.
- Then, attempting to save this `original IpatchDLS2` **corrupted** object a second time leads to a segmentation fault.
=> fix segmentation fault taking its origin during  IpatchDLS2 to file conversion

libinstpatch/IpatchDLSReader.c, libinstpatch/IpatchDLSWriter.c
1)This PR fixes missing initialization after a file has been written.
In ipatch_dls_writer_save():
- the flag `"saved"`, must be set to indicate that the file has been saved.
- the flag `"changed"` must be reset to indicate there is not change.
2)Also after loading a dls file , in ipatch_dls_reader_fixup(), `"changed"` flag is reset. This fix https://github.com/swami/swami/issues/55 point 2.1
=> fix missing flags (saved,changed) initialization

azure-pipelines.yml
Simplify Windows pipeline and make sure to compile XP x86 binaries for x87 FPU only.
=> Windows CI: Compile for IA32

docs/reference/CMakeLists.txt
Fixes warning ”`implicit declaration of function ‘ipatch_init’`” mentioned in https://github.com/swami/libinstpatch/issues/65. This warning could be an error in some C99 and later environments.
Using the `-include` GCC-compatible option to forcibly include the necessary header is a little hacky, but I don’t know a way to add `#include "libinstpatch/misc.h"` to the source of the temporary generated C program directly.
=> Fix warning from libinstpatch-scan.c (gtkdoc)

CMakeLists.txt
Here are the warnings in CMake:
```
CMake Warning (dev) at CMakeLists.txt:9 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Deprecation Warning at CMakeLists.txt:10 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Modify `CMakeLists.txt` to eliminate.
=> Eliminate CMake warnings

libinstpatch/IpatchSampleStoreSndFile.c, libinstpatch/IpatchSampleStoreSndFile.h, libinstpatch/IpatchSndFile.h
Exposing `sndfile.h` in public headers forces depending apps (like fluidsynth) to have libsndfile available at compile time. This breaks the build if e.g. libsndfile is indeed available when building fluidsynth, but fluidsynth rejects it because its version is insufficient.
=> Remove sndfile.h from public headers

libinstpatch/IpatchDLS2Region.c, libinstpatch/IpatchGigRegion.c
In C23 (the default C standard for GCC 15), “bool” is a keyword, so this fixes failure to compile as C23.
=> Rename variables called “bool”
